/* ============================================================
 * words.js — vocabulario de katacan
 *
 * k: palabra en kana (hiragana o katakana; el script se detecta
 *    automáticamente por el primer carácter)
 * j: kanji (null para préstamos sin kanji habitual)
 * c: categoría
 * t: traducciones { es, en, fr, de, pt, it }
 * ============================================================ */

const WORDS = [
  // ---- Animales ----
  { k: 'ねこ', j: '猫', c: 'animals', t: { es: 'gato', en: 'cat', fr: 'chat', de: 'Katze', pt: 'gato', it: 'gatto' } },
  { k: 'いぬ', j: '犬', c: 'animals', t: { es: 'perro', en: 'dog', fr: 'chien', de: 'Hund', pt: 'cachorro', it: 'cane' } },
  { k: 'とり', j: '鳥', c: 'animals', t: { es: 'pájaro', en: 'bird', fr: 'oiseau', de: 'Vogel', pt: 'pássaro', it: 'uccello' } },
  { k: 'さかな', j: '魚', c: 'animals', t: { es: 'pez', en: 'fish', fr: 'poisson', de: 'Fisch', pt: 'peixe', it: 'pesce' } },
  { k: 'うま', j: '馬', c: 'animals', t: { es: 'caballo', en: 'horse', fr: 'cheval', de: 'Pferd', pt: 'cavalo', it: 'cavallo' } },
  { k: 'うし', j: '牛', c: 'animals', t: { es: 'vaca', en: 'cow', fr: 'vache', de: 'Kuh', pt: 'vaca', it: 'mucca' } },
  { k: 'むし', j: '虫', c: 'animals', t: { es: 'insecto', en: 'insect', fr: 'insecte', de: 'Insekt', pt: 'inseto', it: 'insetto' } },
  { k: 'くま', j: '熊', c: 'animals', t: { es: 'oso', en: 'bear', fr: 'ours', de: 'Bär', pt: 'urso', it: 'orso' } },
  { k: 'うさぎ', j: '兎', c: 'animals', t: { es: 'conejo', en: 'rabbit', fr: 'lapin', de: 'Kaninchen', pt: 'coelho', it: 'coniglio' } },
  { k: 'さる', j: '猿', c: 'animals', t: { es: 'mono', en: 'monkey', fr: 'singe', de: 'Affe', pt: 'macaco', it: 'scimmia' } },

  // ---- Comida y bebida ----
  { k: 'ごはん', j: '御飯', c: 'food', t: { es: 'arroz (cocido)', en: 'cooked rice', fr: 'riz (cuit)', de: 'Reis (gekocht)', pt: 'arroz (cozido)', it: 'riso (cotto)' } },
  { k: 'たまご', j: '卵', c: 'food', t: { es: 'huevo', en: 'egg', fr: 'œuf', de: 'Ei', pt: 'ovo', it: 'uovo' } },
  { k: 'にく', j: '肉', c: 'food', t: { es: 'carne', en: 'meat', fr: 'viande', de: 'Fleisch', pt: 'carne', it: 'carne' } },
  { k: 'やさい', j: '野菜', c: 'food', t: { es: 'verduras', en: 'vegetables', fr: 'légumes', de: 'Gemüse', pt: 'legumes', it: 'verdure' } },
  { k: 'くだもの', j: '果物', c: 'food', t: { es: 'fruta', en: 'fruit', fr: 'fruit', de: 'Obst', pt: 'fruta', it: 'frutta' } },
  { k: 'おちゃ', j: 'お茶', c: 'food', t: { es: 'té', en: 'tea', fr: 'thé', de: 'Tee', pt: 'chá', it: 'tè' } },
  { k: 'しお', j: '塩', c: 'food', t: { es: 'sal', en: 'salt', fr: 'sel', de: 'Salz', pt: 'sal', it: 'sale' } },
  { k: 'さとう', j: '砂糖', c: 'food', t: { es: 'azúcar', en: 'sugar', fr: 'sucre', de: 'Zucker', pt: 'açúcar', it: 'zucchero' } },
  { k: 'さけ', j: '酒', c: 'food', t: { es: 'sake', en: 'sake', fr: 'saké', de: 'Sake', pt: 'saquê', it: 'sakè' } },
  { k: 'みず', j: '水', c: 'food', t: { es: 'agua', en: 'water', fr: 'eau', de: 'Wasser', pt: 'água', it: 'acqua' } },
  { k: 'パン', j: null, c: 'food', t: { es: 'pan', en: 'bread', fr: 'pain', de: 'Brot', pt: 'pão', it: 'pane' } },
  { k: 'ケーキ', j: null, c: 'food', t: { es: 'pastel', en: 'cake', fr: 'gâteau', de: 'Kuchen', pt: 'bolo', it: 'torta' } },
  { k: 'アイス', j: null, c: 'food', t: { es: 'helado', en: 'ice cream', fr: 'glace', de: 'Eis', pt: 'sorvete', it: 'gelato' } },
  { k: 'チーズ', j: null, c: 'food', t: { es: 'queso', en: 'cheese', fr: 'fromage', de: 'Käse', pt: 'queijo', it: 'formaggio' } },
  { k: 'チョコレート', j: null, c: 'food', t: { es: 'chocolate', en: 'chocolate', fr: 'chocolat', de: 'Schokolade', pt: 'chocolate', it: 'cioccolato' } },
  { k: 'ピザ', j: null, c: 'food', t: { es: 'pizza', en: 'pizza', fr: 'pizza', de: 'Pizza', pt: 'pizza', it: 'pizza' } },
  { k: 'サラダ', j: null, c: 'food', t: { es: 'ensalada', en: 'salad', fr: 'salade', de: 'Salat', pt: 'salada', it: 'insalata' } },
  { k: 'スープ', j: null, c: 'food', t: { es: 'sopa', en: 'soup', fr: 'soupe', de: 'Suppe', pt: 'sopa', it: 'zuppa' } },
  { k: 'トマト', j: null, c: 'food', t: { es: 'tomate', en: 'tomato', fr: 'tomate', de: 'Tomate', pt: 'tomate', it: 'pomodoro' } },
  { k: 'バナナ', j: null, c: 'food', t: { es: 'plátano', en: 'banana', fr: 'banane', de: 'Banane', pt: 'banana', it: 'banana' } },
  { k: 'コーヒー', j: null, c: 'food', t: { es: 'café', en: 'coffee', fr: 'café', de: 'Kaffee', pt: 'café', it: 'caffè' } },
  { k: 'ミルク', j: null, c: 'food', t: { es: 'leche', en: 'milk', fr: 'lait', de: 'Milch', pt: 'leite', it: 'latte' } },
  { k: 'ジュース', j: null, c: 'food', t: { es: 'jugo', en: 'juice', fr: 'jus', de: 'Saft', pt: 'suco', it: 'succo' } },
  { k: 'ビール', j: null, c: 'food', t: { es: 'cerveza', en: 'beer', fr: 'bière', de: 'Bier', pt: 'cerveja', it: 'birra' } },
  { k: 'ワイン', j: null, c: 'food', t: { es: 'vino', en: 'wine', fr: 'vin', de: 'Wein', pt: 'vinho', it: 'vino' } },

  // ---- Naturaleza ----
  { k: 'やま', j: '山', c: 'nature', t: { es: 'montaña', en: 'mountain', fr: 'montagne', de: 'Berg', pt: 'montanha', it: 'montagna' } },
  { k: 'かわ', j: '川', c: 'nature', t: { es: 'río', en: 'river', fr: 'rivière', de: 'Fluss', pt: 'rio', it: 'fiume' } },
  { k: 'うみ', j: '海', c: 'nature', t: { es: 'mar', en: 'sea', fr: 'mer', de: 'Meer', pt: 'mar', it: 'mare' } },
  { k: 'そら', j: '空', c: 'nature', t: { es: 'cielo', en: 'sky', fr: 'ciel', de: 'Himmel', pt: 'céu', it: 'cielo' } },
  { k: 'つき', j: '月', c: 'nature', t: { es: 'luna', en: 'moon', fr: 'lune', de: 'Mond', pt: 'lua', it: 'luna' } },
  { k: 'ほし', j: '星', c: 'nature', t: { es: 'estrella', en: 'star', fr: 'étoile', de: 'Stern', pt: 'estrela', it: 'stella' } },
  { k: 'たいよう', j: '太陽', c: 'nature', t: { es: 'sol', en: 'sun', fr: 'soleil', de: 'Sonne', pt: 'sol', it: 'sole' } },
  { k: 'はな', j: '花', c: 'nature', t: { es: 'flor', en: 'flower', fr: 'fleur', de: 'Blume', pt: 'flor', it: 'fiore' } },
  { k: 'き', j: '木', c: 'nature', t: { es: 'árbol', en: 'tree', fr: 'arbre', de: 'Baum', pt: 'árvore', it: 'albero' } },
  { k: 'あめ', j: '雨', c: 'nature', t: { es: 'lluvia', en: 'rain', fr: 'pluie', de: 'Regen', pt: 'chuva', it: 'pioggia' } },
  { k: 'ゆき', j: '雪', c: 'nature', t: { es: 'nieve', en: 'snow', fr: 'neige', de: 'Schnee', pt: 'neve', it: 'neve' } },
  { k: 'かぜ', j: '風', c: 'nature', t: { es: 'viento', en: 'wind', fr: 'vent', de: 'Wind', pt: 'vento', it: 'vento' } },
  { k: 'ひ', j: '火', c: 'nature', t: { es: 'fuego', en: 'fire', fr: 'feu', de: 'Feuer', pt: 'fogo', it: 'fuoco' } },
  { k: 'いし', j: '石', c: 'nature', t: { es: 'piedra', en: 'stone', fr: 'pierre', de: 'Stein', pt: 'pedra', it: 'pietra' } },
  { k: 'もり', j: '森', c: 'nature', t: { es: 'bosque', en: 'forest', fr: 'forêt', de: 'Wald', pt: 'floresta', it: 'foresta' } },

  // ---- Cuerpo ----
  { k: 'め', j: '目', c: 'body', t: { es: 'ojo', en: 'eye', fr: 'œil', de: 'Auge', pt: 'olho', it: 'occhio' } },
  { k: 'みみ', j: '耳', c: 'body', t: { es: 'oreja', en: 'ear', fr: 'oreille', de: 'Ohr', pt: 'orelha', it: 'orecchio' } },
  { k: 'くち', j: '口', c: 'body', t: { es: 'boca', en: 'mouth', fr: 'bouche', de: 'Mund', pt: 'boca', it: 'bocca' } },
  { k: 'て', j: '手', c: 'body', t: { es: 'mano', en: 'hand', fr: 'main', de: 'Hand', pt: 'mão', it: 'mano' } },
  { k: 'あし', j: '足', c: 'body', t: { es: 'pie', en: 'foot', fr: 'pied', de: 'Fuß', pt: 'pé', it: 'piede' } },
  { k: 'あたま', j: '頭', c: 'body', t: { es: 'cabeza', en: 'head', fr: 'tête', de: 'Kopf', pt: 'cabeça', it: 'testa' } },
  { k: 'かお', j: '顔', c: 'body', t: { es: 'cara', en: 'face', fr: 'visage', de: 'Gesicht', pt: 'rosto', it: 'viso' } },
  { k: 'こころ', j: '心', c: 'body', t: { es: 'corazón', en: 'heart', fr: 'cœur', de: 'Herz', pt: 'coração', it: 'cuore' } },
  { k: 'は', j: '歯', c: 'body', t: { es: 'diente', en: 'tooth', fr: 'dent', de: 'Zahn', pt: 'dente', it: 'dente' } },
  { k: 'ゆび', j: '指', c: 'body', t: { es: 'dedo', en: 'finger', fr: 'doigt', de: 'Finger', pt: 'dedo', it: 'dito' } },

  // ---- Familia ----
  { k: 'ちち', j: '父', c: 'family', t: { es: 'padre', en: 'father', fr: 'père', de: 'Vater', pt: 'pai', it: 'padre' } },
  { k: 'はは', j: '母', c: 'family', t: { es: 'madre', en: 'mother', fr: 'mère', de: 'Mutter', pt: 'mãe', it: 'madre' } },
  { k: 'あに', j: '兄', c: 'family', t: { es: 'hermano mayor', en: 'older brother', fr: 'grand frère', de: 'älterer Bruder', pt: 'irmão mais velho', it: 'fratello maggiore' } },
  { k: 'あね', j: '姉', c: 'family', t: { es: 'hermana mayor', en: 'older sister', fr: 'grande sœur', de: 'ältere Schwester', pt: 'irmã mais velha', it: 'sorella maggiore' } },
  { k: 'おとうと', j: '弟', c: 'family', t: { es: 'hermano menor', en: 'younger brother', fr: 'petit frère', de: 'jüngerer Bruder', pt: 'irmão mais novo', it: 'fratello minore' } },
  { k: 'いもうと', j: '妹', c: 'family', t: { es: 'hermana menor', en: 'younger sister', fr: 'petite sœur', de: 'jüngere Schwester', pt: 'irmã mais nova', it: 'sorella minore' } },
  { k: 'かぞく', j: '家族', c: 'family', t: { es: 'familia', en: 'family', fr: 'famille', de: 'Familie', pt: 'família', it: 'famiglia' } },
  { k: 'こども', j: '子供', c: 'family', t: { es: 'niño', en: 'child', fr: 'enfant', de: 'Kind', pt: 'criança', it: 'bambino' } },
  { k: 'ともだち', j: '友達', c: 'family', t: { es: 'amigo', en: 'friend', fr: 'ami', de: 'Freund', pt: 'amigo', it: 'amico' } },

  // ---- Tiempo ----
  { k: 'いま', j: '今', c: 'time', t: { es: 'ahora', en: 'now', fr: 'maintenant', de: 'jetzt', pt: 'agora', it: 'adesso' } },
  { k: 'きょう', j: '今日', c: 'time', t: { es: 'hoy', en: 'today', fr: "aujourd'hui", de: 'heute', pt: 'hoje', it: 'oggi' } },
  { k: 'あした', j: '明日', c: 'time', t: { es: 'mañana', en: 'tomorrow', fr: 'demain', de: 'morgen', pt: 'amanhã', it: 'domani' } },
  { k: 'きのう', j: '昨日', c: 'time', t: { es: 'ayer', en: 'yesterday', fr: 'hier', de: 'gestern', pt: 'ontem', it: 'ieri' } },
  { k: 'あさ', j: '朝', c: 'time', t: { es: 'la mañana', en: 'morning', fr: 'matin', de: 'Morgen', pt: 'manhã', it: 'mattina' } },
  { k: 'よる', j: '夜', c: 'time', t: { es: 'noche', en: 'night', fr: 'nuit', de: 'Nacht', pt: 'noite', it: 'notte' } },
  { k: 'ひる', j: '昼', c: 'time', t: { es: 'mediodía', en: 'midday', fr: 'midi', de: 'Mittag', pt: 'meio-dia', it: 'mezzogiorno' } },
  { k: 'とき', j: '時', c: 'time', t: { es: 'tiempo, momento', en: 'time, moment', fr: 'temps, moment', de: 'Zeit, Moment', pt: 'tempo, momento', it: 'tempo, momento' } },
  { k: 'はる', j: '春', c: 'time', t: { es: 'primavera', en: 'spring', fr: 'printemps', de: 'Frühling', pt: 'primavera', it: 'primavera' } },
  { k: 'なつ', j: '夏', c: 'time', t: { es: 'verano', en: 'summer', fr: 'été', de: 'Sommer', pt: 'verão', it: 'estate' } },
  { k: 'あき', j: '秋', c: 'time', t: { es: 'otoño', en: 'autumn', fr: 'automne', de: 'Herbst', pt: 'outono', it: 'autunno' } },
  { k: 'ふゆ', j: '冬', c: 'time', t: { es: 'invierno', en: 'winter', fr: 'hiver', de: 'Winter', pt: 'inverno', it: 'inverno' } },

  // ---- Colores ----
  { k: 'あか', j: '赤', c: 'colors', t: { es: 'rojo', en: 'red', fr: 'rouge', de: 'Rot', pt: 'vermelho', it: 'rosso' } },
  { k: 'あお', j: '青', c: 'colors', t: { es: 'azul', en: 'blue', fr: 'bleu', de: 'Blau', pt: 'azul', it: 'blu' } },
  { k: 'しろ', j: '白', c: 'colors', t: { es: 'blanco', en: 'white', fr: 'blanc', de: 'Weiß', pt: 'branco', it: 'bianco' } },
  { k: 'くろ', j: '黒', c: 'colors', t: { es: 'negro', en: 'black', fr: 'noir', de: 'Schwarz', pt: 'preto', it: 'nero' } },
  { k: 'みどり', j: '緑', c: 'colors', t: { es: 'verde', en: 'green', fr: 'vert', de: 'Grün', pt: 'verde', it: 'verde' } },
  { k: 'きいろ', j: '黄色', c: 'colors', t: { es: 'amarillo', en: 'yellow', fr: 'jaune', de: 'Gelb', pt: 'amarelo', it: 'giallo' } },

  // ---- Objetos ----
  { k: 'ほん', j: '本', c: 'objects', t: { es: 'libro', en: 'book', fr: 'livre', de: 'Buch', pt: 'livro', it: 'libro' } },
  { k: 'かばん', j: '鞄', c: 'objects', t: { es: 'bolso', en: 'bag', fr: 'sac', de: 'Tasche', pt: 'bolsa', it: 'borsa' } },
  { k: 'くるま', j: '車', c: 'objects', t: { es: 'coche', en: 'car', fr: 'voiture', de: 'Auto', pt: 'carro', it: 'macchina' } },
  { k: 'つくえ', j: '机', c: 'objects', t: { es: 'escritorio', en: 'desk', fr: 'bureau', de: 'Schreibtisch', pt: 'escrivaninha', it: 'scrivania' } },
  { k: 'いす', j: '椅子', c: 'objects', t: { es: 'silla', en: 'chair', fr: 'chaise', de: 'Stuhl', pt: 'cadeira', it: 'sedia' } },
  { k: 'かさ', j: '傘', c: 'objects', t: { es: 'paraguas', en: 'umbrella', fr: 'parapluie', de: 'Regenschirm', pt: 'guarda-chuva', it: 'ombrello' } },
  { k: 'とけい', j: '時計', c: 'objects', t: { es: 'reloj', en: 'clock, watch', fr: 'montre, horloge', de: 'Uhr', pt: 'relógio', it: 'orologio' } },
  { k: 'でんわ', j: '電話', c: 'objects', t: { es: 'teléfono', en: 'telephone', fr: 'téléphone', de: 'Telefon', pt: 'telefone', it: 'telefono' } },
  { k: 'かぎ', j: '鍵', c: 'objects', t: { es: 'llave', en: 'key', fr: 'clé', de: 'Schlüssel', pt: 'chave', it: 'chiave' } },
  { k: 'ふく', j: '服', c: 'objects', t: { es: 'ropa', en: 'clothes', fr: 'vêtements', de: 'Kleidung', pt: 'roupa', it: 'vestiti' } },
  { k: 'くつ', j: '靴', c: 'objects', t: { es: 'zapatos', en: 'shoes', fr: 'chaussures', de: 'Schuhe', pt: 'sapatos', it: 'scarpe' } },
  { k: 'めがね', j: '眼鏡', c: 'objects', t: { es: 'gafas', en: 'glasses', fr: 'lunettes', de: 'Brille', pt: 'óculos', it: 'occhiali' } },
  { k: 'カメラ', j: null, c: 'objects', t: { es: 'cámara', en: 'camera', fr: 'appareil photo', de: 'Kamera', pt: 'câmera', it: 'fotocamera' } },
  { k: 'テレビ', j: null, c: 'objects', t: { es: 'televisión', en: 'TV', fr: 'télévision', de: 'Fernseher', pt: 'televisão', it: 'televisione' } },
  { k: 'パソコン', j: null, c: 'objects', t: { es: 'computadora', en: 'computer', fr: 'ordinateur', de: 'Computer', pt: 'computador', it: 'computer' } },
  { k: 'スマホ', j: null, c: 'objects', t: { es: 'celular', en: 'smartphone', fr: 'smartphone', de: 'Smartphone', pt: 'celular', it: 'smartphone' } },
  { k: 'ドア', j: null, c: 'objects', t: { es: 'puerta', en: 'door', fr: 'porte', de: 'Tür', pt: 'porta', it: 'porta' } },
  { k: 'テーブル', j: null, c: 'objects', t: { es: 'mesa', en: 'table', fr: 'table', de: 'Tisch', pt: 'mesa', it: 'tavolo' } },
  { k: 'ベッド', j: null, c: 'objects', t: { es: 'cama', en: 'bed', fr: 'lit', de: 'Bett', pt: 'cama', it: 'letto' } },
  { k: 'ゲーム', j: null, c: 'objects', t: { es: 'juego', en: 'game', fr: 'jeu', de: 'Spiel', pt: 'jogo', it: 'gioco' } },
  { k: 'メール', j: null, c: 'objects', t: { es: 'correo electrónico', en: 'email', fr: 'e-mail', de: 'E-Mail', pt: 'e-mail', it: 'email' } },
  { k: 'ギター', j: null, c: 'objects', t: { es: 'guitarra', en: 'guitar', fr: 'guitare', de: 'Gitarre', pt: 'guitarra', it: 'chitarra' } },
  { k: 'ピアノ', j: null, c: 'objects', t: { es: 'piano', en: 'piano', fr: 'piano', de: 'Klavier', pt: 'piano', it: 'pianoforte' } },
  { k: 'シャツ', j: null, c: 'objects', t: { es: 'camisa', en: 'shirt', fr: 'chemise', de: 'Hemd', pt: 'camisa', it: 'camicia' } },
  { k: 'スカート', j: null, c: 'objects', t: { es: 'falda', en: 'skirt', fr: 'jupe', de: 'Rock', pt: 'saia', it: 'gonna' } },
  { k: 'コート', j: null, c: 'objects', t: { es: 'abrigo', en: 'coat', fr: 'manteau', de: 'Mantel', pt: 'casaco', it: 'cappotto' } },

  // ---- Lugares ----
  { k: 'いえ', j: '家', c: 'places', t: { es: 'casa', en: 'house', fr: 'maison', de: 'Haus', pt: 'casa', it: 'casa' } },
  { k: 'がっこう', j: '学校', c: 'places', t: { es: 'escuela', en: 'school', fr: 'école', de: 'Schule', pt: 'escola', it: 'scuola' } },
  { k: 'えき', j: '駅', c: 'places', t: { es: 'estación', en: 'station', fr: 'gare', de: 'Bahnhof', pt: 'estação', it: 'stazione' } },
  { k: 'みせ', j: '店', c: 'places', t: { es: 'tienda', en: 'shop', fr: 'magasin', de: 'Geschäft', pt: 'loja', it: 'negozio' } },
  { k: 'まち', j: '町', c: 'places', t: { es: 'ciudad', en: 'town', fr: 'ville', de: 'Stadt', pt: 'cidade', it: 'città' } },
  { k: 'くに', j: '国', c: 'places', t: { es: 'país', en: 'country', fr: 'pays', de: 'Land', pt: 'país', it: 'paese' } },
  { k: 'びょういん', j: '病院', c: 'places', t: { es: 'hospital', en: 'hospital', fr: 'hôpital', de: 'Krankenhaus', pt: 'hospital', it: 'ospedale' } },
  { k: 'ぎんこう', j: '銀行', c: 'places', t: { es: 'banco', en: 'bank', fr: 'banque', de: 'Bank', pt: 'banco', it: 'banca' } },
  { k: 'こうえん', j: '公園', c: 'places', t: { es: 'parque', en: 'park', fr: 'parc', de: 'Park', pt: 'parque', it: 'parco' } },
  { k: 'みち', j: '道', c: 'places', t: { es: 'camino', en: 'road, way', fr: 'chemin', de: 'Weg', pt: 'caminho', it: 'strada' } },
  { k: 'でんしゃ', j: '電車', c: 'places', t: { es: 'tren', en: 'train', fr: 'train', de: 'Zug', pt: 'trem', it: 'treno' } },
  { k: 'レストラン', j: null, c: 'places', t: { es: 'restaurante', en: 'restaurant', fr: 'restaurant', de: 'Restaurant', pt: 'restaurante', it: 'ristorante' } },
  { k: 'ホテル', j: null, c: 'places', t: { es: 'hotel', en: 'hotel', fr: 'hôtel', de: 'Hotel', pt: 'hotel', it: 'albergo' } },
  { k: 'プール', j: null, c: 'places', t: { es: 'piscina', en: 'pool', fr: 'piscine', de: 'Schwimmbad', pt: 'piscina', it: 'piscina' } },
  { k: 'バス', j: null, c: 'places', t: { es: 'autobús', en: 'bus', fr: 'bus', de: 'Bus', pt: 'ônibus', it: 'autobus' } },
  { k: 'タクシー', j: null, c: 'places', t: { es: 'taxi', en: 'taxi', fr: 'taxi', de: 'Taxi', pt: 'táxi', it: 'taxi' } },

  // ---- Verbos ----
  { k: 'たべる', j: '食べる', c: 'verbs', t: { es: 'comer', en: 'to eat', fr: 'manger', de: 'essen', pt: 'comer', it: 'mangiare' } },
  { k: 'のむ', j: '飲む', c: 'verbs', t: { es: 'beber', en: 'to drink', fr: 'boire', de: 'trinken', pt: 'beber', it: 'bere' } },
  { k: 'みる', j: '見る', c: 'verbs', t: { es: 'ver', en: 'to see', fr: 'voir', de: 'sehen', pt: 'ver', it: 'vedere' } },
  { k: 'きく', j: '聞く', c: 'verbs', t: { es: 'escuchar', en: 'to listen', fr: 'écouter', de: 'hören', pt: 'ouvir', it: 'ascoltare' } },
  { k: 'はなす', j: '話す', c: 'verbs', t: { es: 'hablar', en: 'to speak', fr: 'parler', de: 'sprechen', pt: 'falar', it: 'parlare' } },
  { k: 'よむ', j: '読む', c: 'verbs', t: { es: 'leer', en: 'to read', fr: 'lire', de: 'lesen', pt: 'ler', it: 'leggere' } },
  { k: 'かく', j: '書く', c: 'verbs', t: { es: 'escribir', en: 'to write', fr: 'écrire', de: 'schreiben', pt: 'escrever', it: 'scrivere' } },
  { k: 'いく', j: '行く', c: 'verbs', t: { es: 'ir', en: 'to go', fr: 'aller', de: 'gehen', pt: 'ir', it: 'andare' } },
  { k: 'くる', j: '来る', c: 'verbs', t: { es: 'venir', en: 'to come', fr: 'venir', de: 'kommen', pt: 'vir', it: 'venire' } },
  { k: 'ねる', j: '寝る', c: 'verbs', t: { es: 'dormir', en: 'to sleep', fr: 'dormir', de: 'schlafen', pt: 'dormir', it: 'dormire' } },
  { k: 'かう', j: '買う', c: 'verbs', t: { es: 'comprar', en: 'to buy', fr: 'acheter', de: 'kaufen', pt: 'comprar', it: 'comprare' } },
  { k: 'あるく', j: '歩く', c: 'verbs', t: { es: 'caminar', en: 'to walk', fr: 'marcher', de: 'laufen', pt: 'caminhar', it: 'camminare' } },
  { k: 'はしる', j: '走る', c: 'verbs', t: { es: 'correr', en: 'to run', fr: 'courir', de: 'rennen', pt: 'correr', it: 'correre' } },
  { k: 'つくる', j: '作る', c: 'verbs', t: { es: 'hacer, fabricar', en: 'to make', fr: 'faire, fabriquer', de: 'machen', pt: 'fazer', it: 'fare, creare' } },

  // ---- Adjetivos ----
  { k: 'おおきい', j: '大きい', c: 'adjectives', t: { es: 'grande', en: 'big', fr: 'grand', de: 'groß', pt: 'grande', it: 'grande' } },
  { k: 'ちいさい', j: '小さい', c: 'adjectives', t: { es: 'pequeño', en: 'small', fr: 'petit', de: 'klein', pt: 'pequeno', it: 'piccolo' } },
  { k: 'たかい', j: '高い', c: 'adjectives', t: { es: 'caro; alto', en: 'expensive; tall', fr: 'cher ; haut', de: 'teuer; hoch', pt: 'caro; alto', it: 'caro; alto' } },
  { k: 'やすい', j: '安い', c: 'adjectives', t: { es: 'barato', en: 'cheap', fr: 'pas cher', de: 'billig', pt: 'barato', it: 'economico' } },
  { k: 'あたらしい', j: '新しい', c: 'adjectives', t: { es: 'nuevo', en: 'new', fr: 'nouveau', de: 'neu', pt: 'novo', it: 'nuovo' } },
  { k: 'ふるい', j: '古い', c: 'adjectives', t: { es: 'viejo', en: 'old', fr: 'vieux', de: 'alt', pt: 'velho', it: 'vecchio' } },
  { k: 'はやい', j: '速い', c: 'adjectives', t: { es: 'rápido', en: 'fast', fr: 'rapide', de: 'schnell', pt: 'rápido', it: 'veloce' } },
  { k: 'おそい', j: '遅い', c: 'adjectives', t: { es: 'lento', en: 'slow', fr: 'lent', de: 'langsam', pt: 'lento', it: 'lento' } },
  { k: 'あつい', j: '暑い', c: 'adjectives', t: { es: 'caluroso', en: 'hot (weather)', fr: 'chaud', de: 'heiß', pt: 'quente', it: 'caldo' } },
  { k: 'さむい', j: '寒い', c: 'adjectives', t: { es: 'frío', en: 'cold (weather)', fr: 'froid', de: 'kalt', pt: 'frio', it: 'freddo' } },
  { k: 'たのしい', j: '楽しい', c: 'adjectives', t: { es: 'divertido', en: 'fun', fr: 'amusant', de: 'lustig', pt: 'divertido', it: 'divertente' } },
  { k: 'おいしい', j: '美味しい', c: 'adjectives', t: { es: 'delicioso', en: 'delicious', fr: 'délicieux', de: 'lecker', pt: 'delicioso', it: 'delizioso' } },
  { k: 'むずかしい', j: '難しい', c: 'adjectives', t: { es: 'difícil', en: 'difficult', fr: 'difficile', de: 'schwierig', pt: 'difícil', it: 'difficile' } },
  { k: 'やさしい', j: '優しい', c: 'adjectives', t: { es: 'amable', en: 'kind', fr: 'gentil', de: 'nett', pt: 'gentil', it: 'gentile' } },
];

const CATEGORIES = ['animals', 'food', 'nature', 'body', 'family', 'time', 'colors', 'objects', 'places', 'verbs', 'adjectives'];

if (typeof module !== 'undefined') module.exports = { WORDS, CATEGORIES };
