/** Vocabulario de katacan: 157 palabras en 11 categorías, 6 idiomas. */
import type { Word } from './types'

export const WORDS: Word[] = [
  { kana: 'ねこ', kanji: '猫', category: 'animals', translations: { es: 'gato', en: 'cat', fr: 'chat', de: 'Katze', pt: 'gato', it: 'gatto' } },
  { kana: 'いぬ', kanji: '犬', category: 'animals', translations: { es: 'perro', en: 'dog', fr: 'chien', de: 'Hund', pt: 'cachorro', it: 'cane' } },
  { kana: 'とり', kanji: '鳥', category: 'animals', translations: { es: 'pájaro', en: 'bird', fr: 'oiseau', de: 'Vogel', pt: 'pássaro', it: 'uccello' } },
  { kana: 'さかな', kanji: '魚', category: 'animals', translations: { es: 'pez', en: 'fish', fr: 'poisson', de: 'Fisch', pt: 'peixe', it: 'pesce' } },
  { kana: 'うま', kanji: '馬', category: 'animals', translations: { es: 'caballo', en: 'horse', fr: 'cheval', de: 'Pferd', pt: 'cavalo', it: 'cavallo' } },
  { kana: 'うし', kanji: '牛', category: 'animals', translations: { es: 'vaca', en: 'cow', fr: 'vache', de: 'Kuh', pt: 'vaca', it: 'mucca' } },
  { kana: 'むし', kanji: '虫', category: 'animals', translations: { es: 'insecto', en: 'insect', fr: 'insecte', de: 'Insekt', pt: 'inseto', it: 'insetto' } },
  { kana: 'くま', kanji: '熊', category: 'animals', translations: { es: 'oso', en: 'bear', fr: 'ours', de: 'Bär', pt: 'urso', it: 'orso' } },
  { kana: 'うさぎ', kanji: '兎', category: 'animals', translations: { es: 'conejo', en: 'rabbit', fr: 'lapin', de: 'Kaninchen', pt: 'coelho', it: 'coniglio' } },
  { kana: 'さる', kanji: '猿', category: 'animals', translations: { es: 'mono', en: 'monkey', fr: 'singe', de: 'Affe', pt: 'macaco', it: 'scimmia' } },
  { kana: 'ごはん', kanji: '御飯', category: 'food', translations: { es: 'arroz (cocido)', en: 'cooked rice', fr: 'riz (cuit)', de: 'Reis (gekocht)', pt: 'arroz (cozido)', it: 'riso (cotto)' } },
  { kana: 'たまご', kanji: '卵', category: 'food', translations: { es: 'huevo', en: 'egg', fr: 'œuf', de: 'Ei', pt: 'ovo', it: 'uovo' } },
  { kana: 'にく', kanji: '肉', category: 'food', translations: { es: 'carne', en: 'meat', fr: 'viande', de: 'Fleisch', pt: 'carne', it: 'carne' } },
  { kana: 'やさい', kanji: '野菜', category: 'food', translations: { es: 'verduras', en: 'vegetables', fr: 'légumes', de: 'Gemüse', pt: 'legumes', it: 'verdure' } },
  { kana: 'くだもの', kanji: '果物', category: 'food', translations: { es: 'fruta', en: 'fruit', fr: 'fruit', de: 'Obst', pt: 'fruta', it: 'frutta' } },
  { kana: 'おちゃ', kanji: 'お茶', category: 'food', translations: { es: 'té', en: 'tea', fr: 'thé', de: 'Tee', pt: 'chá', it: 'tè' } },
  { kana: 'しお', kanji: '塩', category: 'food', translations: { es: 'sal', en: 'salt', fr: 'sel', de: 'Salz', pt: 'sal', it: 'sale' } },
  { kana: 'さとう', kanji: '砂糖', category: 'food', translations: { es: 'azúcar', en: 'sugar', fr: 'sucre', de: 'Zucker', pt: 'açúcar', it: 'zucchero' } },
  { kana: 'さけ', kanji: '酒', category: 'food', translations: { es: 'sake', en: 'sake', fr: 'saké', de: 'Sake', pt: 'saquê', it: 'sakè' } },
  { kana: 'みず', kanji: '水', category: 'food', translations: { es: 'agua', en: 'water', fr: 'eau', de: 'Wasser', pt: 'água', it: 'acqua' } },
  { kana: 'パン', kanji: null, category: 'food', translations: { es: 'pan', en: 'bread', fr: 'pain', de: 'Brot', pt: 'pão', it: 'pane' } },
  { kana: 'ケーキ', kanji: null, category: 'food', translations: { es: 'pastel', en: 'cake', fr: 'gâteau', de: 'Kuchen', pt: 'bolo', it: 'torta' } },
  { kana: 'アイス', kanji: null, category: 'food', translations: { es: 'helado', en: 'ice cream', fr: 'glace', de: 'Eis', pt: 'sorvete', it: 'gelato' } },
  { kana: 'チーズ', kanji: null, category: 'food', translations: { es: 'queso', en: 'cheese', fr: 'fromage', de: 'Käse', pt: 'queijo', it: 'formaggio' } },
  { kana: 'チョコレート', kanji: null, category: 'food', translations: { es: 'chocolate', en: 'chocolate', fr: 'chocolat', de: 'Schokolade', pt: 'chocolate', it: 'cioccolato' } },
  { kana: 'ピザ', kanji: null, category: 'food', translations: { es: 'pizza', en: 'pizza', fr: 'pizza', de: 'Pizza', pt: 'pizza', it: 'pizza' } },
  { kana: 'サラダ', kanji: null, category: 'food', translations: { es: 'ensalada', en: 'salad', fr: 'salade', de: 'Salat', pt: 'salada', it: 'insalata' } },
  { kana: 'スープ', kanji: null, category: 'food', translations: { es: 'sopa', en: 'soup', fr: 'soupe', de: 'Suppe', pt: 'sopa', it: 'zuppa' } },
  { kana: 'トマト', kanji: null, category: 'food', translations: { es: 'tomate', en: 'tomato', fr: 'tomate', de: 'Tomate', pt: 'tomate', it: 'pomodoro' } },
  { kana: 'バナナ', kanji: null, category: 'food', translations: { es: 'plátano', en: 'banana', fr: 'banane', de: 'Banane', pt: 'banana', it: 'banana' } },
  { kana: 'コーヒー', kanji: null, category: 'food', translations: { es: 'café', en: 'coffee', fr: 'café', de: 'Kaffee', pt: 'café', it: 'caffè' } },
  { kana: 'ミルク', kanji: null, category: 'food', translations: { es: 'leche', en: 'milk', fr: 'lait', de: 'Milch', pt: 'leite', it: 'latte' } },
  { kana: 'ジュース', kanji: null, category: 'food', translations: { es: 'jugo', en: 'juice', fr: 'jus', de: 'Saft', pt: 'suco', it: 'succo' } },
  { kana: 'ビール', kanji: null, category: 'food', translations: { es: 'cerveza', en: 'beer', fr: 'bière', de: 'Bier', pt: 'cerveja', it: 'birra' } },
  { kana: 'ワイン', kanji: null, category: 'food', translations: { es: 'vino', en: 'wine', fr: 'vin', de: 'Wein', pt: 'vinho', it: 'vino' } },
  { kana: 'やま', kanji: '山', category: 'nature', translations: { es: 'montaña', en: 'mountain', fr: 'montagne', de: 'Berg', pt: 'montanha', it: 'montagna' } },
  { kana: 'かわ', kanji: '川', category: 'nature', translations: { es: 'río', en: 'river', fr: 'rivière', de: 'Fluss', pt: 'rio', it: 'fiume' } },
  { kana: 'うみ', kanji: '海', category: 'nature', translations: { es: 'mar', en: 'sea', fr: 'mer', de: 'Meer', pt: 'mar', it: 'mare' } },
  { kana: 'そら', kanji: '空', category: 'nature', translations: { es: 'cielo', en: 'sky', fr: 'ciel', de: 'Himmel', pt: 'céu', it: 'cielo' } },
  { kana: 'つき', kanji: '月', category: 'nature', translations: { es: 'luna', en: 'moon', fr: 'lune', de: 'Mond', pt: 'lua', it: 'luna' } },
  { kana: 'ほし', kanji: '星', category: 'nature', translations: { es: 'estrella', en: 'star', fr: 'étoile', de: 'Stern', pt: 'estrela', it: 'stella' } },
  { kana: 'たいよう', kanji: '太陽', category: 'nature', translations: { es: 'sol', en: 'sun', fr: 'soleil', de: 'Sonne', pt: 'sol', it: 'sole' } },
  { kana: 'はな', kanji: '花', category: 'nature', translations: { es: 'flor', en: 'flower', fr: 'fleur', de: 'Blume', pt: 'flor', it: 'fiore' } },
  { kana: 'き', kanji: '木', category: 'nature', translations: { es: 'árbol', en: 'tree', fr: 'arbre', de: 'Baum', pt: 'árvore', it: 'albero' } },
  { kana: 'あめ', kanji: '雨', category: 'nature', translations: { es: 'lluvia', en: 'rain', fr: 'pluie', de: 'Regen', pt: 'chuva', it: 'pioggia' } },
  { kana: 'ゆき', kanji: '雪', category: 'nature', translations: { es: 'nieve', en: 'snow', fr: 'neige', de: 'Schnee', pt: 'neve', it: 'neve' } },
  { kana: 'かぜ', kanji: '風', category: 'nature', translations: { es: 'viento', en: 'wind', fr: 'vent', de: 'Wind', pt: 'vento', it: 'vento' } },
  { kana: 'ひ', kanji: '火', category: 'nature', translations: { es: 'fuego', en: 'fire', fr: 'feu', de: 'Feuer', pt: 'fogo', it: 'fuoco' } },
  { kana: 'いし', kanji: '石', category: 'nature', translations: { es: 'piedra', en: 'stone', fr: 'pierre', de: 'Stein', pt: 'pedra', it: 'pietra' } },
  { kana: 'もり', kanji: '森', category: 'nature', translations: { es: 'bosque', en: 'forest', fr: 'forêt', de: 'Wald', pt: 'floresta', it: 'foresta' } },
  { kana: 'め', kanji: '目', category: 'body', translations: { es: 'ojo', en: 'eye', fr: 'œil', de: 'Auge', pt: 'olho', it: 'occhio' } },
  { kana: 'みみ', kanji: '耳', category: 'body', translations: { es: 'oreja', en: 'ear', fr: 'oreille', de: 'Ohr', pt: 'orelha', it: 'orecchio' } },
  { kana: 'くち', kanji: '口', category: 'body', translations: { es: 'boca', en: 'mouth', fr: 'bouche', de: 'Mund', pt: 'boca', it: 'bocca' } },
  { kana: 'て', kanji: '手', category: 'body', translations: { es: 'mano', en: 'hand', fr: 'main', de: 'Hand', pt: 'mão', it: 'mano' } },
  { kana: 'あし', kanji: '足', category: 'body', translations: { es: 'pie', en: 'foot', fr: 'pied', de: 'Fuß', pt: 'pé', it: 'piede' } },
  { kana: 'あたま', kanji: '頭', category: 'body', translations: { es: 'cabeza', en: 'head', fr: 'tête', de: 'Kopf', pt: 'cabeça', it: 'testa' } },
  { kana: 'かお', kanji: '顔', category: 'body', translations: { es: 'cara', en: 'face', fr: 'visage', de: 'Gesicht', pt: 'rosto', it: 'viso' } },
  { kana: 'こころ', kanji: '心', category: 'body', translations: { es: 'corazón', en: 'heart', fr: 'cœur', de: 'Herz', pt: 'coração', it: 'cuore' } },
  { kana: 'は', kanji: '歯', category: 'body', translations: { es: 'diente', en: 'tooth', fr: 'dent', de: 'Zahn', pt: 'dente', it: 'dente' } },
  { kana: 'ゆび', kanji: '指', category: 'body', translations: { es: 'dedo', en: 'finger', fr: 'doigt', de: 'Finger', pt: 'dedo', it: 'dito' } },
  { kana: 'ちち', kanji: '父', category: 'family', translations: { es: 'padre', en: 'father', fr: 'père', de: 'Vater', pt: 'pai', it: 'padre' } },
  { kana: 'はは', kanji: '母', category: 'family', translations: { es: 'madre', en: 'mother', fr: 'mère', de: 'Mutter', pt: 'mãe', it: 'madre' } },
  { kana: 'あに', kanji: '兄', category: 'family', translations: { es: 'hermano mayor', en: 'older brother', fr: 'grand frère', de: 'älterer Bruder', pt: 'irmão mais velho', it: 'fratello maggiore' } },
  { kana: 'あね', kanji: '姉', category: 'family', translations: { es: 'hermana mayor', en: 'older sister', fr: 'grande sœur', de: 'ältere Schwester', pt: 'irmã mais velha', it: 'sorella maggiore' } },
  { kana: 'おとうと', kanji: '弟', category: 'family', translations: { es: 'hermano menor', en: 'younger brother', fr: 'petit frère', de: 'jüngerer Bruder', pt: 'irmão mais novo', it: 'fratello minore' } },
  { kana: 'いもうと', kanji: '妹', category: 'family', translations: { es: 'hermana menor', en: 'younger sister', fr: 'petite sœur', de: 'jüngere Schwester', pt: 'irmã mais nova', it: 'sorella minore' } },
  { kana: 'かぞく', kanji: '家族', category: 'family', translations: { es: 'familia', en: 'family', fr: 'famille', de: 'Familie', pt: 'família', it: 'famiglia' } },
  { kana: 'こども', kanji: '子供', category: 'family', translations: { es: 'niño', en: 'child', fr: 'enfant', de: 'Kind', pt: 'criança', it: 'bambino' } },
  { kana: 'ともだち', kanji: '友達', category: 'family', translations: { es: 'amigo', en: 'friend', fr: 'ami', de: 'Freund', pt: 'amigo', it: 'amico' } },
  { kana: 'いま', kanji: '今', category: 'time', translations: { es: 'ahora', en: 'now', fr: 'maintenant', de: 'jetzt', pt: 'agora', it: 'adesso' } },
  { kana: 'きょう', kanji: '今日', category: 'time', translations: { es: 'hoy', en: 'today', fr: 'aujourd\'hui', de: 'heute', pt: 'hoje', it: 'oggi' } },
  { kana: 'あした', kanji: '明日', category: 'time', translations: { es: 'mañana', en: 'tomorrow', fr: 'demain', de: 'morgen', pt: 'amanhã', it: 'domani' } },
  { kana: 'きのう', kanji: '昨日', category: 'time', translations: { es: 'ayer', en: 'yesterday', fr: 'hier', de: 'gestern', pt: 'ontem', it: 'ieri' } },
  { kana: 'あさ', kanji: '朝', category: 'time', translations: { es: 'la mañana', en: 'morning', fr: 'matin', de: 'Morgen', pt: 'manhã', it: 'mattina' } },
  { kana: 'よる', kanji: '夜', category: 'time', translations: { es: 'noche', en: 'night', fr: 'nuit', de: 'Nacht', pt: 'noite', it: 'notte' } },
  { kana: 'ひる', kanji: '昼', category: 'time', translations: { es: 'mediodía', en: 'midday', fr: 'midi', de: 'Mittag', pt: 'meio-dia', it: 'mezzogiorno' } },
  { kana: 'とき', kanji: '時', category: 'time', translations: { es: 'tiempo, momento', en: 'time, moment', fr: 'temps, moment', de: 'Zeit, Moment', pt: 'tempo, momento', it: 'tempo, momento' } },
  { kana: 'はる', kanji: '春', category: 'time', translations: { es: 'primavera', en: 'spring', fr: 'printemps', de: 'Frühling', pt: 'primavera', it: 'primavera' } },
  { kana: 'なつ', kanji: '夏', category: 'time', translations: { es: 'verano', en: 'summer', fr: 'été', de: 'Sommer', pt: 'verão', it: 'estate' } },
  { kana: 'あき', kanji: '秋', category: 'time', translations: { es: 'otoño', en: 'autumn', fr: 'automne', de: 'Herbst', pt: 'outono', it: 'autunno' } },
  { kana: 'ふゆ', kanji: '冬', category: 'time', translations: { es: 'invierno', en: 'winter', fr: 'hiver', de: 'Winter', pt: 'inverno', it: 'inverno' } },
  { kana: 'あか', kanji: '赤', category: 'colors', translations: { es: 'rojo', en: 'red', fr: 'rouge', de: 'Rot', pt: 'vermelho', it: 'rosso' } },
  { kana: 'あお', kanji: '青', category: 'colors', translations: { es: 'azul', en: 'blue', fr: 'bleu', de: 'Blau', pt: 'azul', it: 'blu' } },
  { kana: 'しろ', kanji: '白', category: 'colors', translations: { es: 'blanco', en: 'white', fr: 'blanc', de: 'Weiß', pt: 'branco', it: 'bianco' } },
  { kana: 'くろ', kanji: '黒', category: 'colors', translations: { es: 'negro', en: 'black', fr: 'noir', de: 'Schwarz', pt: 'preto', it: 'nero' } },
  { kana: 'みどり', kanji: '緑', category: 'colors', translations: { es: 'verde', en: 'green', fr: 'vert', de: 'Grün', pt: 'verde', it: 'verde' } },
  { kana: 'きいろ', kanji: '黄色', category: 'colors', translations: { es: 'amarillo', en: 'yellow', fr: 'jaune', de: 'Gelb', pt: 'amarelo', it: 'giallo' } },
  { kana: 'ほん', kanji: '本', category: 'objects', translations: { es: 'libro', en: 'book', fr: 'livre', de: 'Buch', pt: 'livro', it: 'libro' } },
  { kana: 'かばん', kanji: '鞄', category: 'objects', translations: { es: 'bolso', en: 'bag', fr: 'sac', de: 'Tasche', pt: 'bolsa', it: 'borsa' } },
  { kana: 'くるま', kanji: '車', category: 'objects', translations: { es: 'coche', en: 'car', fr: 'voiture', de: 'Auto', pt: 'carro', it: 'macchina' } },
  { kana: 'つくえ', kanji: '机', category: 'objects', translations: { es: 'escritorio', en: 'desk', fr: 'bureau', de: 'Schreibtisch', pt: 'escrivaninha', it: 'scrivania' } },
  { kana: 'いす', kanji: '椅子', category: 'objects', translations: { es: 'silla', en: 'chair', fr: 'chaise', de: 'Stuhl', pt: 'cadeira', it: 'sedia' } },
  { kana: 'かさ', kanji: '傘', category: 'objects', translations: { es: 'paraguas', en: 'umbrella', fr: 'parapluie', de: 'Regenschirm', pt: 'guarda-chuva', it: 'ombrello' } },
  { kana: 'とけい', kanji: '時計', category: 'objects', translations: { es: 'reloj', en: 'clock, watch', fr: 'montre, horloge', de: 'Uhr', pt: 'relógio', it: 'orologio' } },
  { kana: 'でんわ', kanji: '電話', category: 'objects', translations: { es: 'teléfono', en: 'telephone', fr: 'téléphone', de: 'Telefon', pt: 'telefone', it: 'telefono' } },
  { kana: 'かぎ', kanji: '鍵', category: 'objects', translations: { es: 'llave', en: 'key', fr: 'clé', de: 'Schlüssel', pt: 'chave', it: 'chiave' } },
  { kana: 'ふく', kanji: '服', category: 'objects', translations: { es: 'ropa', en: 'clothes', fr: 'vêtements', de: 'Kleidung', pt: 'roupa', it: 'vestiti' } },
  { kana: 'くつ', kanji: '靴', category: 'objects', translations: { es: 'zapatos', en: 'shoes', fr: 'chaussures', de: 'Schuhe', pt: 'sapatos', it: 'scarpe' } },
  { kana: 'めがね', kanji: '眼鏡', category: 'objects', translations: { es: 'gafas', en: 'glasses', fr: 'lunettes', de: 'Brille', pt: 'óculos', it: 'occhiali' } },
  { kana: 'カメラ', kanji: null, category: 'objects', translations: { es: 'cámara', en: 'camera', fr: 'appareil photo', de: 'Kamera', pt: 'câmera', it: 'fotocamera' } },
  { kana: 'テレビ', kanji: null, category: 'objects', translations: { es: 'televisión', en: 'TV', fr: 'télévision', de: 'Fernseher', pt: 'televisão', it: 'televisione' } },
  { kana: 'パソコン', kanji: null, category: 'objects', translations: { es: 'computadora', en: 'computer', fr: 'ordinateur', de: 'Computer', pt: 'computador', it: 'computer' } },
  { kana: 'スマホ', kanji: null, category: 'objects', translations: { es: 'celular', en: 'smartphone', fr: 'smartphone', de: 'Smartphone', pt: 'celular', it: 'smartphone' } },
  { kana: 'ドア', kanji: null, category: 'objects', translations: { es: 'puerta', en: 'door', fr: 'porte', de: 'Tür', pt: 'porta', it: 'porta' } },
  { kana: 'テーブル', kanji: null, category: 'objects', translations: { es: 'mesa', en: 'table', fr: 'table', de: 'Tisch', pt: 'mesa', it: 'tavolo' } },
  { kana: 'ベッド', kanji: null, category: 'objects', translations: { es: 'cama', en: 'bed', fr: 'lit', de: 'Bett', pt: 'cama', it: 'letto' } },
  { kana: 'ゲーム', kanji: null, category: 'objects', translations: { es: 'juego', en: 'game', fr: 'jeu', de: 'Spiel', pt: 'jogo', it: 'gioco' } },
  { kana: 'メール', kanji: null, category: 'objects', translations: { es: 'correo electrónico', en: 'email', fr: 'e-mail', de: 'E-Mail', pt: 'e-mail', it: 'email' } },
  { kana: 'ギター', kanji: null, category: 'objects', translations: { es: 'guitarra', en: 'guitar', fr: 'guitare', de: 'Gitarre', pt: 'guitarra', it: 'chitarra' } },
  { kana: 'ピアノ', kanji: null, category: 'objects', translations: { es: 'piano', en: 'piano', fr: 'piano', de: 'Klavier', pt: 'piano', it: 'pianoforte' } },
  { kana: 'シャツ', kanji: null, category: 'objects', translations: { es: 'camisa', en: 'shirt', fr: 'chemise', de: 'Hemd', pt: 'camisa', it: 'camicia' } },
  { kana: 'スカート', kanji: null, category: 'objects', translations: { es: 'falda', en: 'skirt', fr: 'jupe', de: 'Rock', pt: 'saia', it: 'gonna' } },
  { kana: 'コート', kanji: null, category: 'objects', translations: { es: 'abrigo', en: 'coat', fr: 'manteau', de: 'Mantel', pt: 'casaco', it: 'cappotto' } },
  { kana: 'いえ', kanji: '家', category: 'places', translations: { es: 'casa', en: 'house', fr: 'maison', de: 'Haus', pt: 'casa', it: 'casa' } },
  { kana: 'がっこう', kanji: '学校', category: 'places', translations: { es: 'escuela', en: 'school', fr: 'école', de: 'Schule', pt: 'escola', it: 'scuola' } },
  { kana: 'えき', kanji: '駅', category: 'places', translations: { es: 'estación', en: 'station', fr: 'gare', de: 'Bahnhof', pt: 'estação', it: 'stazione' } },
  { kana: 'みせ', kanji: '店', category: 'places', translations: { es: 'tienda', en: 'shop', fr: 'magasin', de: 'Geschäft', pt: 'loja', it: 'negozio' } },
  { kana: 'まち', kanji: '町', category: 'places', translations: { es: 'ciudad', en: 'town', fr: 'ville', de: 'Stadt', pt: 'cidade', it: 'città' } },
  { kana: 'くに', kanji: '国', category: 'places', translations: { es: 'país', en: 'country', fr: 'pays', de: 'Land', pt: 'país', it: 'paese' } },
  { kana: 'びょういん', kanji: '病院', category: 'places', translations: { es: 'hospital', en: 'hospital', fr: 'hôpital', de: 'Krankenhaus', pt: 'hospital', it: 'ospedale' } },
  { kana: 'ぎんこう', kanji: '銀行', category: 'places', translations: { es: 'banco', en: 'bank', fr: 'banque', de: 'Bank', pt: 'banco', it: 'banca' } },
  { kana: 'こうえん', kanji: '公園', category: 'places', translations: { es: 'parque', en: 'park', fr: 'parc', de: 'Park', pt: 'parque', it: 'parco' } },
  { kana: 'みち', kanji: '道', category: 'places', translations: { es: 'camino', en: 'road, way', fr: 'chemin', de: 'Weg', pt: 'caminho', it: 'strada' } },
  { kana: 'でんしゃ', kanji: '電車', category: 'places', translations: { es: 'tren', en: 'train', fr: 'train', de: 'Zug', pt: 'trem', it: 'treno' } },
  { kana: 'レストラン', kanji: null, category: 'places', translations: { es: 'restaurante', en: 'restaurant', fr: 'restaurant', de: 'Restaurant', pt: 'restaurante', it: 'ristorante' } },
  { kana: 'ホテル', kanji: null, category: 'places', translations: { es: 'hotel', en: 'hotel', fr: 'hôtel', de: 'Hotel', pt: 'hotel', it: 'albergo' } },
  { kana: 'プール', kanji: null, category: 'places', translations: { es: 'piscina', en: 'pool', fr: 'piscine', de: 'Schwimmbad', pt: 'piscina', it: 'piscina' } },
  { kana: 'バス', kanji: null, category: 'places', translations: { es: 'autobús', en: 'bus', fr: 'bus', de: 'Bus', pt: 'ônibus', it: 'autobus' } },
  { kana: 'タクシー', kanji: null, category: 'places', translations: { es: 'taxi', en: 'taxi', fr: 'taxi', de: 'Taxi', pt: 'táxi', it: 'taxi' } },
  { kana: 'たべる', kanji: '食べる', category: 'verbs', translations: { es: 'comer', en: 'to eat', fr: 'manger', de: 'essen', pt: 'comer', it: 'mangiare' } },
  { kana: 'のむ', kanji: '飲む', category: 'verbs', translations: { es: 'beber', en: 'to drink', fr: 'boire', de: 'trinken', pt: 'beber', it: 'bere' } },
  { kana: 'みる', kanji: '見る', category: 'verbs', translations: { es: 'ver', en: 'to see', fr: 'voir', de: 'sehen', pt: 'ver', it: 'vedere' } },
  { kana: 'きく', kanji: '聞く', category: 'verbs', translations: { es: 'escuchar', en: 'to listen', fr: 'écouter', de: 'hören', pt: 'ouvir', it: 'ascoltare' } },
  { kana: 'はなす', kanji: '話す', category: 'verbs', translations: { es: 'hablar', en: 'to speak', fr: 'parler', de: 'sprechen', pt: 'falar', it: 'parlare' } },
  { kana: 'よむ', kanji: '読む', category: 'verbs', translations: { es: 'leer', en: 'to read', fr: 'lire', de: 'lesen', pt: 'ler', it: 'leggere' } },
  { kana: 'かく', kanji: '書く', category: 'verbs', translations: { es: 'escribir', en: 'to write', fr: 'écrire', de: 'schreiben', pt: 'escrever', it: 'scrivere' } },
  { kana: 'いく', kanji: '行く', category: 'verbs', translations: { es: 'ir', en: 'to go', fr: 'aller', de: 'gehen', pt: 'ir', it: 'andare' } },
  { kana: 'くる', kanji: '来る', category: 'verbs', translations: { es: 'venir', en: 'to come', fr: 'venir', de: 'kommen', pt: 'vir', it: 'venire' } },
  { kana: 'ねる', kanji: '寝る', category: 'verbs', translations: { es: 'dormir', en: 'to sleep', fr: 'dormir', de: 'schlafen', pt: 'dormir', it: 'dormire' } },
  { kana: 'かう', kanji: '買う', category: 'verbs', translations: { es: 'comprar', en: 'to buy', fr: 'acheter', de: 'kaufen', pt: 'comprar', it: 'comprare' } },
  { kana: 'あるく', kanji: '歩く', category: 'verbs', translations: { es: 'caminar', en: 'to walk', fr: 'marcher', de: 'laufen', pt: 'caminhar', it: 'camminare' } },
  { kana: 'はしる', kanji: '走る', category: 'verbs', translations: { es: 'correr', en: 'to run', fr: 'courir', de: 'rennen', pt: 'correr', it: 'correre' } },
  { kana: 'つくる', kanji: '作る', category: 'verbs', translations: { es: 'hacer, fabricar', en: 'to make', fr: 'faire, fabriquer', de: 'machen', pt: 'fazer', it: 'fare, creare' } },
  { kana: 'おおきい', kanji: '大きい', category: 'adjectives', translations: { es: 'grande', en: 'big', fr: 'grand', de: 'groß', pt: 'grande', it: 'grande' } },
  { kana: 'ちいさい', kanji: '小さい', category: 'adjectives', translations: { es: 'pequeño', en: 'small', fr: 'petit', de: 'klein', pt: 'pequeno', it: 'piccolo' } },
  { kana: 'たかい', kanji: '高い', category: 'adjectives', translations: { es: 'caro; alto', en: 'expensive; tall', fr: 'cher ; haut', de: 'teuer; hoch', pt: 'caro; alto', it: 'caro; alto' } },
  { kana: 'やすい', kanji: '安い', category: 'adjectives', translations: { es: 'barato', en: 'cheap', fr: 'pas cher', de: 'billig', pt: 'barato', it: 'economico' } },
  { kana: 'あたらしい', kanji: '新しい', category: 'adjectives', translations: { es: 'nuevo', en: 'new', fr: 'nouveau', de: 'neu', pt: 'novo', it: 'nuovo' } },
  { kana: 'ふるい', kanji: '古い', category: 'adjectives', translations: { es: 'viejo', en: 'old', fr: 'vieux', de: 'alt', pt: 'velho', it: 'vecchio' } },
  { kana: 'はやい', kanji: '速い', category: 'adjectives', translations: { es: 'rápido', en: 'fast', fr: 'rapide', de: 'schnell', pt: 'rápido', it: 'veloce' } },
  { kana: 'おそい', kanji: '遅い', category: 'adjectives', translations: { es: 'lento', en: 'slow', fr: 'lent', de: 'langsam', pt: 'lento', it: 'lento' } },
  { kana: 'あつい', kanji: '暑い', category: 'adjectives', translations: { es: 'caluroso', en: 'hot (weather)', fr: 'chaud', de: 'heiß', pt: 'quente', it: 'caldo' } },
  { kana: 'さむい', kanji: '寒い', category: 'adjectives', translations: { es: 'frío', en: 'cold (weather)', fr: 'froid', de: 'kalt', pt: 'frio', it: 'freddo' } },
  { kana: 'たのしい', kanji: '楽しい', category: 'adjectives', translations: { es: 'divertido', en: 'fun', fr: 'amusant', de: 'lustig', pt: 'divertido', it: 'divertente' } },
  { kana: 'おいしい', kanji: '美味しい', category: 'adjectives', translations: { es: 'delicioso', en: 'delicious', fr: 'délicieux', de: 'lecker', pt: 'delicioso', it: 'delizioso' } },
  { kana: 'むずかしい', kanji: '難しい', category: 'adjectives', translations: { es: 'difícil', en: 'difficult', fr: 'difficile', de: 'schwierig', pt: 'difícil', it: 'difficile' } },
  { kana: 'やさしい', kanji: '優しい', category: 'adjectives', translations: { es: 'amable', en: 'kind', fr: 'gentil', de: 'nett', pt: 'gentil', it: 'gentile' } },
]
